@echo off

if %COMSPEC_X64_VER%0 NEQ 0 goto CONEMU_CMDLINE_X64
goto CONEMU_CMDLINE_X86

:CONEMU_CMDLINE_X64
set CONEMU_CMDLINE_ATTACH_PREFIX=%CONEMU_CMD64_CMDLINE_ATTACH_PREFIX%
set CONEMU_CMDLINE_RUN_PREFIX=%CONEMU_CMD64_CMDLINE_RUN_PREFIX%

exit /b 0

:CONEMU_CMDLINE_X86
set CONEMU_CMDLINE_ATTACH_PREFIX=%CONEMU_CMD32_CMDLINE_ATTACH_PREFIX%
set CONEMU_CMDLINE_RUN_PREFIX=%CONEMU_CMD32_CMDLINE_RUN_PREFIX%

exit /b 0
