# based on: https://github.com/andry81/github-accum-stats
#

name: totalcmd plugin downloads updating every 4 hours

on:
  schedule:
    - cron: "0 */4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-totalcmd-plugin-downloads:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: andry81/gh-action--accum-inpage-downloads@master
        with:
          # CAUTION: Beware of double quotes strip in case of usage yaml `>-` operator or even a single-quotted string!
          query_url:                http://totalcmd.net/plugring/tacklebar.html
          downloads_sed_regexp:     s/.*Downloaded:[^0-9]*([0-9.]+).*/\1/p

          curl_flags: >-
            -H 'Cache-Control: no-cache'

          deps_repo_owner:          andry81
          stat_entity_path:         plugring/tacklebar

          output_repo_owner:        andry81
          output_repo:              tacklebar--totalcmd-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/downloads/plugin
          output_repo_write_token:  ${{ secrets.READ_STATS_TOKEN }}
