name: totalcmd board stats updating every 4 hours

on:
  schedule:
    - cron: "0 */4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  traffic-board-stats:
    runs-on: ubuntu-latest

    env:
      traffic_totalcmd_board_stats_json: traffic/totalcmd_board_stats.json
      topic_query_url: https://www.ghisler.ch/board/search.php?keywords="%5BExtension%5D+Tacklebar"&terms=all&author=andry81&fid%5B%5D=6&sc=0&sf=titleonly&sr=topics&sk=i&sd=d&st=0&ch=1&t=0&submit=Search

    steps:
      - name: allocate directories
        run: |
          mkdir $GITHUB_WORKSPACE/gh-workflow $GITHUB_WORKSPACE/totalcmd-stats

      - name: checkout gh-workflow
        uses: actions/checkout@v2
        with:
          repository: 'andry81/gh-workflow'
          path: gh-workflow

      - name: checkout totalcmd-stats
        uses: actions/checkout@v2
        with:
          repository: 'andry81/tacklebar--totalcmd-stats'
          path: totalcmd-stats
          token: ${{ secrets.SECRET_TOKEN }}

      - name: request traffic board stats json
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/totalcmd-stats
          chmod ug+x $GITHUB_WORKSPACE/gh-workflow/bash/totalcmd/extract-board-stats.sh
          $GITHUB_WORKSPACE/gh-workflow/bash/totalcmd/extract-board-stats.sh

      - name: commit totalcmd-stats
        run: |
          cd $GITHUB_WORKSPACE/totalcmd-stats
          git add .
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Automated traffic/board-stats update"

      - name: push totalcmd-stats
        uses: ad-m/github-push-action@master
        with:
          repository: 'andry81/tacklebar--totalcmd-stats'
          directory: totalcmd-stats
          github_token: ${{ secrets.SECRET_TOKEN }}
