name: GitHub Clone Count for 14 days at every 8 hours

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 */8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  traffic-clones:
    runs-on: ubuntu-latest

    env:
      traffic_clones_json: traffic/clones.json
      traffic_clones_accum_json: traffic/clones-accum.json

    steps:
      - name: allocate directories
        run: |
          mkdir $GITHUB_WORKSPACE/gh-workflow $GITHUB_WORKSPACE/gh-stats

      - run: |
          cd $GITHUB_WORKSPACE/gh-workflow

      - name: checkout gh-workflow
        uses: actions/checkout@v2
        with:
          repository: 'andry81/gh-workflow'
          path: $GITHUB_WORKSPACE/gh-workflow

      - run: |
          cd $GITHUB_WORKSPACE/gh-stats

      - name: checkout gh-stats
        uses: actions/checkout@v2
        with:
          repository: 'andry81/tacklebar--gh-stats'
          path: $GITHUB_WORKSPACE/gh-stats

      - name: request traffic clones json
        run: |
          curl --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/andry81/tacklebar/traffic/clones \
            > "$traffic_clones_json"

      - name: accumulate traffic clones
        shell: bash
        run: |
          $GITHUB_WORKSPACE/gh-workflow/bash/accum-traffic-clones.sh

      - name: commit gh-stats
        run: |
          git add .
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Automated traffic/clones update"

      - name: push gh-stats
        uses: ad-m/github-push-action@master
        with:
          repository: 'andry81/tacklebar--gh-stats'
          github_token: ${{ secrets.SECRET_TOKEN }}
